Default: &defaults
  database: rage-gaming.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: rage-gaming_test.sqlite3
  <<: *defaults

Staging:
  database: rage-gaming_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: rage-gaming_production.sqlite3
  poolsize: 100
  <<: *defaults
